name: Ntfy-Notification

on:
  push:
    branches: [main]
  pull_request:

jobs:
  enforce-all-checks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: GitHub Checks
        uses: poseidon/wait-for-status-checks@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  on-success:
    runs-on: ubuntu-latest
    steps:
      - name: Successfull message
        run: |
          curl \
          -u ${{ secrets.NTFY_CRED }} \
          -H "Title: Check suite completed successfully" \
          -H "Content-Type: text/plain" \
          -d $'Repo: ${{ github.repository }}\nPR: ${{ github.event.check_suite.pull_requests.number }}\nCommit: ${{ github.sha }}\nRef: ${{ github.ref }}\nStatus: ${{ github.event.check_suite.conclusion }}' \
          ${{ secrets.NTFY_URL }}
  on-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Failed message
        run: |
          curl \
          -u ${{ secrets.NTFY_CRED }} \
          -H "Title: Rigit Compilation failed" \
          -H "Content-Type: text/plain" \
          -d $'Repo: ${{ github.repository }}\nPR: ${{ github.event.check_suite.pull_requests.number }}\nCommit: ${{ github.sha }}\nRef: ${{ github.ref }}\nStatus: ${{ github.event.check_suite.conclusion }}' \
          ${{ secrets.NTFY_URL }}
