name: Ntfy-Notification

on:
  check_suite:
    types: [completed]

jobs:
  on-success:
    if: ${{ github.event.check_suite.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Successfull message
        run: |
          curl \
          -u ${{ secrets.NTFY_CRED }} \
          -H "Title: Check suite completed successfully" \
          -H "Content-Type: text/plain" \
          -d $'Repo: ${{ github.repository }}\nURL: ${{ github.event.check_suite.check_runs_url }}\nCommit: ${{ github.sha }}\nRef: ${{ github.ref }}\nStatus: ${{ github.event.check_suite.conclusion }}' \
          ${{ secrets.NTFY_URL }}
  on-failure:
    if: ${{ github.event.check_suite.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Failed message
        run: |
          curl \
          -u ${{ secrets.NTFY_CRED }} \
          -H "Title: Rigit Compilation failed" \
          -H "Content-Type: text/plain" \
          -d $'Repo: ${{ github.repository }}\nURL: ${{ github.event.check_suite.check_runs_url }}\nCommit: ${{ github.sha }}\nRef: ${{ github.ref }}\nStatus: ${{ github.event.check_suite.conclusion }}' \
          ${{ secrets.NTFY_URL }}
